### ISSUE TITLE
[1.6.0.43-testing-win64] Error when attempting to remove player

### ISSUE THREAD

**Issue by Geethebluesky** [Podshot/MCEdit-Unified-Preview#13]
Tried removing the "single player" from a server map that had been previously generated as a singleplayer map. Got this:

```
Traceback (most recent call last):
  File "mceutils.py", line 53, in _alertException
  File "editortools\player.py", line 631, in removePlayer
  File "leveleditor.py", line 3146, in addOperation
  File "leveleditor.py", line 3157, in performWithRetry
  File "editortools\player.py", line 70, in perform
ValueError: list.remove(x): x not in list
```

**Comment by Podshot** [comment]
I’ll look into it!
