### ISSUE TITLE
Error opening 1.4.2 world: Blocks: Data does not match the required 4096 bytes length: 587 bytes

### ISSUE THREAD

**Issue by DomPrice** [Podshot/MCEdit-Unified-Preview#14]
Error thrown: 

mcedit.main MCEdit exited with errors.
[   ERROR][                   root.py:951]:MCEdit version Unified v1.6.0.20-testing %s Minecraft 1.8-1.11.2 | PE 0.11
[   ERROR][                   root.py:954]:Blocks: Data does not match the required 4096 bytes length: 587 bytes
Traceback (most recent call last):
  File "mcedit.py", line 948, in main
  File "mcedit.py", line 825, in main
  File "albow\root.py", line 168, in run
  File "albow\root.py", line 233, in run_modal
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 763, in gl_draw_all
  File "albow\openglwidgets.py", line 22, in gl_draw_self
  File "albow\openglwidgets.py", line 28, in gl_draw_viewport
  File "viewports\camera.py", line 1909, in gl_draw
  File "viewports\camera.py", line 1931, in render
  File "viewports\camera.py", line 346, in updateBlockFaceUnderCursor
  File "raycaster.py", line 85, in firstBlock
  File "pymclevel\infiniteworld.py", line 532, in blockAt
  File "pymclevel\leveldbpocket.py", line 954, in getChunk
  File "pymclevel\leveldbpocket.py", line 589, in loadChunk
  File "pymclevel\leveldbpocket.py", line 453, in _readChunk
  File "pymclevel\leveldbpocket.py", line 1891, in add_data
  File "pymclevel\leveldbpocket.py", line 1744, in add_data
ValueError: Blocks: Data does not match the required 4096 bytes length: 587 bytes
Press RETURN or close this window to dismiss.

**Comment by DomPrice** [comment]
Disregard, error was fixed in 1.6.0.49
