### ISSUE TITLE
Bedrock v1.14 Crash

### ISSUE THREAD

**Issue by JoelUrena** [Podshot/MCEdit-Unified-Preview#23]
Exception TypeError: TypeError("No array-type handler for type <type 'numpy.uint32'> (value: 6) registered",) in <bound method Texture.__del__ of <glutils.Texture object at 0x0000024121819C88>> ignored
Exception TypeError: TypeError("No array-type handler for type <type 'numpy.uint32'> (value: 7) registered",) in <bound method Texture.__del__ of <glutils.Texture object at 0x0000024121819D68>> ignored

Game Version: PE : 1.14.1.5.0
mcedit.main MCEdit exited with errors.
[   ERROR][                  root.py:1013]:MCEdit version Unified v1.6.0.53-testing %s Minecraft 1.8-1.11.2 | PE 0.11
[   ERROR][                  root.py:1016]:'Key val not found.'
Traceback (most recent call last):
  File "mcedit.py", line 1010, in main
  File "mcedit.py", line 887, in main
  File "albow\root.py", line 174, in run
  File "albow\root.py", line 239, in run_modal
  File "albow\widget.py", line 804, in gl_draw_all
  File "albow\widget.py", line 804, in gl_draw_all
  File "albow\widget.py", line 804, in gl_draw_all
  File "albow\widget.py", line 804, in gl_draw_all
  File "albow\widget.py", line 801, in gl_draw_all
  File "albow\openglwidgets.py", line 22, in gl_draw_self
  File "albow\openglwidgets.py", line 28, in gl_draw_viewport
  File "viewports\camera.py", line 1922, in gl_draw
  File "viewports\chunk.py", line 83, in render
  File "viewports\camera.py", line 1944, in render
  File "viewports\camera.py", line 349, in updateBlockFaceUnderCursor
  File "viewports\camera.py", line 426, in _findBlockFaceUnderCursor
  File "pymclevel\infiniteworld.py", line 547, in blockAt
  File "pymclevel\leveldbpocket.py", line 1003, in getChunk
  File "pymclevel\leveldbpocket.py", line 655, in loadChunk
  File "pymclevel\leveldbpocket.py", line 470, in _readChunk
  File "pymclevel\leveldbpocket.py", line 1971, in add_data
  File "pymclevel\leveldbpocket.py", line 1925, in _read_block_storage
  File "pymclevel\_nbt.pyx", line 478, in pymclevel._nbt._TAG_Compound.__getitem__
    raise KeyError("Key %s not found." % key)
KeyError: 'Key val not found.'
Press RETURN or close this window to dismiss.

**Comment by kacesensitive** [comment]
Bump

**Comment by PyroThrive** [comment]
Yep, same thing no matter how many tries I do it.

**Comment by PyroThrive** [comment]
https://www.youtube.com/watch?v=UBWqT_yyptQ 

follow this video it worked for me.
