### ISSUE TITLE
Crash when moving Player location

### ISSUE THREAD

**Issue by abrightmoore** [Podshot/MCEdit-Unified-Preview#5]
I just tried to move Player in 1.6.0.18 and it crashed:

```Exception TypeError: TypeError("No array-type handler for type <type 'numpy.uint32'> (value: 10941) registered",) in <bound method Texture.__del__ of <glutils.Texture object at 0x0000014598A16DD8>> ignored
Exception TypeError: TypeError("No array-type handler for type <type 'numpy.uint32'> (value: 10942) registered",) in <bound method Texture.__del__ of <glutils.Texture object at 0x0000014598A16FD0>> ignored
mcedit.main MCEdit exited with errors.
[   ERROR][                   root.py:951]:MCEdit version Unified v1.6.0.18-testing %s Minecraft 1.8-1.11.2 | PE 0.11
[   ERROR][                   root.py:954]:'Player'
Traceback (most recent call last):
  File "mcedit.py", line 948, in main
  File "mcedit.py", line 825, in main
  File "albow\root.py", line 168, in run
  File "albow\root.py", line 233, in run_modal
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 763, in gl_draw_all
  File "albow\openglwidgets.py", line 22, in gl_draw_self
  File "albow\openglwidgets.py", line 28, in gl_draw_viewport
  File "viewports\camera.py", line 1909, in gl_draw
  File "viewports\camera.py", line 1946, in render
  File "editortools\player.py", line 844, in drawToolReticle
KeyError: 'Player'
Press RETURN or close this window to dismiss.```

I know it's old... but is mostly stable!

**Comment by Podshot** [comment]
I'll take a look into it!
