### ISSUE TITLE
Issues with 1.6.0.23 and the test versions before that one.

### ISSUE THREAD

**Issue by DestructiveBurn** [Podshot/MCEdit-Unified-Preview#8]
Some Issues
1) Item names are duplicated in the search.
2) When rotating the selected chunks it hangs for over a second or more.  It's not instant like v1.5.6.0 is.  I'm used to fast speeds and having a delay is really annoying. 
3) Comparing to v1.5.6.0 loading chunks at a large view distance is a lot slower in the test versions.
Over time it ends up so slow you're forced to quit the program and reload it so it renders faster.

I'm using Minecraft Java Edition 1.12.2 with Windows 7 64-bit.
Please fix these issues.   So far everything else seems to be good.   The only reason why I'm using this test version is that of the new blocks like concrete.  v1.5.6.0 is way behind on that and that version has rotation issue errors on some Redstone but it's by far faster.

**Comment by Podshot** [comment]
Thank you for your bug report, we'll work on this as soon as we can. For future reference, please submit any bugs that don't directly relate to starting a MCEdit testing build [here](https://github.com/Podshot/MCEdit-Unified/issues).

**Comment by DestructiveBurn** [comment]
Thanks for a reply back.   I'll hold you to your word on "we'll work on this as soon as we can"   I hope for the next version. 

Thanks for the link.  I'll use that now on.   I hope that won't be the case.

**Comment by DomPrice** [comment]
Tried to open a 1.4.2. world in 1.6.0.20... got this error. Cannot open world.

mcedit.main MCEdit exited with errors.
[   ERROR][                   root.py:951]:MCEdit version Unified v1.6.0.20-testing %s Minecraft 1.8-1.11.2 | PE 0.11
[   ERROR][                   root.py:954]:Blocks: Data does not match the required 4096 bytes length: 587 bytes
Traceback (most recent call last):
  File "mcedit.py", line 948, in main
  File "mcedit.py", line 825, in main
  File "albow\root.py", line 168, in run
  File "albow\root.py", line 233, in run_modal
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 766, in gl_draw_all
  File "albow\widget.py", line 763, in gl_draw_all
  File "albow\openglwidgets.py", line 22, in gl_draw_self
  File "albow\openglwidgets.py", line 28, in gl_draw_viewport
  File "viewports\camera.py", line 1909, in gl_draw
  File "viewports\camera.py", line 1931, in render
  File "viewports\camera.py", line 346, in updateBlockFaceUnderCursor
  File "raycaster.py", line 85, in firstBlock
  File "pymclevel\infiniteworld.py", line 532, in blockAt
  File "pymclevel\leveldbpocket.py", line 954, in getChunk
  File "pymclevel\leveldbpocket.py", line 589, in loadChunk
  File "pymclevel\leveldbpocket.py", line 453, in _readChunk
  File "pymclevel\leveldbpocket.py", line 1891, in add_data
  File "pymclevel\leveldbpocket.py", line 1744, in add_data
ValueError: Blocks: Data does not match the required 4096 bytes length: 587 bytes
Press RETURN or close this window to dismiss.
